@Documind_HostAddress = http://localhost:5231

### Ingest Text
# @name IngestText
POST {{Documind_HostAddress}}/api/ingest
Content-Type: text/plain

This is a sample document to be ingested. It can be a long text.